# fly.toml app configuration file generated for email-checker on 2023-09-04T03:41:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "email-checker"
primary_region = "atl"

[build]

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
