[tool.poetry]
name = "trampoline"
version = "0.99.0"
description = "Check emails?"
authors = ["Srikanth Gopalakrishnan <srikanth.gokr@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dnspython = "^2.4.2"
fastapi = "^0.103.2"
disposable-email-domains = "^0.0.95"
pydantic = {extras = ["email"], version = "^2.5.3"}
hypercorn = "^0.14.4"
sentry-sdk = {extras = ["fastapi"], version = "^1.39.0"}
rich = "^13.7.0"
pendulum = "^3.0.0"
orjson = "^3.9.10"
brotli-asgi = "^1.4.0"
aiosmtplib = "^2.0.2"
acme-tiny = "^5.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ruff = "^0.1.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
