[tool.poetry]
name = "email-verify"
version = "0.1.0"
description = "Check emails?"
authors = ["Srikanth Gopalakrishnan <srikanth.gokr@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dnspython = "^2.4.2"
fastapi = "^0.103.0"
disposable-email-domains = "^0.0.95"
pydantic = {extras = ["email"], version = "^2.3.0"}
hypercorn = "^0.14.4"

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
ruff = "^0.0.287"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
